### PR TITLE
3.1.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
Lots of new work, plus some approved PRs waiting to go. Shall we assemble a new release of this package? Happy to do the merges/testing etc., if everyone thinks this is ready?

### CODE REVIEW

**Comment by tsimbalar** [comment]
Quite happy to merge "as is". 

Within the remaining PRs, here is my take on it : 

- 🔴  #169 "Configuration File Path Edited" : not sure we want it yet, considering changes that we still have on develop branch (may overlap with #159 )
- ⚠️  #162 "LoggingFilterSwitch support" : right now, adds support for `"FilterSwitches": { "$filterSwitch": "Application = 'Sample'" },` - could be merged "as is", but there was an ongoing discussion about whether we should use it as an opportunity to declare a more generic `Switches` (see https://github.com/serilog/serilog-settings-configuration/pull/162#issuecomment-453251028 )
- ✅  #163 "Added new ReadFrom.Configuration(...) overloads; Marked old as obsolete" : ready to merge, I believe
- ✅  #155 "Exceptions when misconfigured" : good to merge
- ⚠️  #141 "only build packaging-related commits" : I think there was a higher level discussions going on in https://github.com/serilog/serilog/issues/1224 , so it's not quite ready yet


We may want to already increase the version number to `v3.1` on the dev branch 👍

**Comment by tsimbalar** [comment]
Should we merge what we have and make a `v3.1` out of it (before we actually forget what the changes we have were all about :P) ? 

I think we should : 
- bump the minor version (`3.0.1` ➡️ `3.1.0`) on `dev`
- merge to dev the following PRs : 
  - https://github.com/serilog/serilog-settings-configuration/pull/176 (tests only, low risk)
  - https://github.com/serilog/serilog-settings-configuration/pull/163 (marks old overloads as obsolete)
  - https://github.com/serilog/serilog-settings-configuration/pull/155 (clearer errors in `SelfLog` when a configuration method was not found
- merge to `master` when we want

Once this is pushed out the door, we can quietly review what to do with : 
- #169 
- #162 
- #141 

What do you think ?

**Comment by nblumhardt** [comment]
Sounds like a plan, @tsimbalar !

I've merged the three you suggested, and once the build completes I'll make the release 👍

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-settings-configuration/releases/tag/v3.1.0

👏

**Pull request merged**
