### PR TITLE
Fix build script and move approval test into new project

### PR DESCRIPTION
**Pull request by sungam3r**
See https://github.com/serilog/serilog/pull/1887 . I moved approval test into new project to align build process with core repo.

### CODE REVIEW

**Comment by SimonCropp** [comment]
why split out approval test?

**Comment by sungam3r** [comment]
To align build process with core repo where approval test is in own project.

**Comment by SimonCropp** [comment]
i would argue the core project should have i merged back into the main test project @nblumhardt

**Comment by 0xced** [comment]
If merged, this will break my efforts to [run tests in parallel on AppVeyor](https://github.com/0xced/serilog-settings-configuration/commit/e71c5494fcbdae33cd105e1b1a1733f3e6ceb8fc) which works around https://github.com/dotnet/sdk/issues/19147.

**Comment by sungam3r** [comment]
> i would argue the core project should have i merged back into the main test project

I'm fine either way.

**Comment by nblumhardt** [comment]
I've just added approval tests to Serilog.Sinks.OpenTelemetry directly in the main unit test project. Needing to rely on an additional assertions library (Shouldly) is a marginal negative but probably not enough to justify the additional project, since we're already very relaxed about test project dependencies.

Seems like this one should be closed RE the parallel testing effort; if it needs more consideration or reopening please just sing out :)

**Pull request closed without merging**
