### PR TITLE
Support of constructor parameters

### PR DESCRIPTION
**Pull request by vhatsura**
related to #167 

Hey, guys! It's an early draft pull request with implementation of possiblity to create object via constructors with parameters. I will be appreciate if you can take a look and add your feedback

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks! Short on time but will try to loop back around. What was the situation in which you found yourself needing this? (I've seen several :+1:)

**Comment by vhatsura** [comment]
In my case I use [`ExceptionAsObjectJsonFormatter`](https://github.com/serilog/serilog-sinks-elasticsearch/blob/729b506c0a13aa44ff17b5029291cc79e8cb3527/src/Serilog.Formatting.Elasticsearch/ExceptionAsObjectJsonFormatter.cs#L29) from `Serilog.Formatting.Elasticsearch`. The formatter has a lot of arguments and sometimes we need to override them. This is why ability to configure constructor arguments in configuration is nice to have

**Comment by julealgon** [comment]
@nblumhardt , what's the status on this? I just stumbled upon this problem today when introducing file logging in one of our solutions, and realizing I needed to set the `renderMessage` argument on `JsonFormatter` to `true`.

Would be really useful to have first-class support for configuring complex/abstract instances with parameters in config files.

**Comment by tsimbalar** [comment]
@julealgon for now, you might want to use a workaround such as the one described in 
https://github.com/serilog/serilog-sinks-console/issues/28

or follow indications in https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md#interfaces-and-abstract-classes , and make a `Formatter` configured the way you want it either as : 
- a custom class with a default constructor
- a static property on your own type

**Comment by tzographos** [comment]
> @julealgon for now, you might want to use a workaround such as the one described in
> [serilog/serilog-sinks-console#28](https://github.com/serilog/serilog-sinks-console/issues/28)

Hello @tsimbalar. How's this solving the problem where there is a need to configure a TextFormatter with constructor arguments (non-parameterless constructor)?

**Comment by tsimbalar** [comment]
@tzographos you're right, there is nothing about this in https://github.com/serilog/serilog-sinks-console/issues/28 ... no idea what I meant back then 🤔

**Comment by skomis-mm** [comment]
Ok, I've just created the [new one](https://github.com/serilog/serilog-settings-configuration/pull/281) with additional features. Feel free to comment/review :)

**Pull request closed without merging**
