### PR TITLE
7.0.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #233 - minimum level configuration improvements (@HexHunter97)
 * #301 - support for delegate type arguments (@almostchristian)
 * #326 - README improvements (@nblumhardt)
 * #333 - extension method discovery that goes easier on Dynatrace (@skomis-mm)
 * #334 - case-insensitive level support (@skomis-mm)
 * #342 - implicit `using` and file-scoped namespaces (@sungam3r)
 * #344 - clean-up (@sungam3r)
 * #351 - drop .NET 4.5.1 support (@0xced)
 * #348 - additional `IFormatProvider` support (@0xced)
 * #354, #357 - improve tests using raw string literals (@sungam3r)
 * #352 - `OnLevelSwitchCreated` callback (@0xced)
 * #355 - add `global.json` (@SimonCropp)
 * #356 - use `Directory.Build.props` (@SimonCropp)
 * #359 - update test refs (@SimonCropp)
 * #360 - remove redundant project settings (@SimonCropp)
 * #358 - build on macOS (@SimonCropp)
 * #361 - add API approval tests (@sungam3r)
 * #362 - support for reading configuration from `IConfigurationSection` contents (@sungam3r)
 * #364 - nullable reference type fixes (@0xced)
 * #367 - improve tests using raw string literals (@0xced)
 * #369 - more nullable reference type safety (@0xced)
 * #363 - allow configuration using internal types and methods (@sungam3r)
 * #368 - improve `SelfLog` output (@sungam3r)
 * #375 - fix README example (@DevAlvaroF)
 * #377 - pin to `Microsoft.Extensions.Configuration` v7 (@nblumhardt)
 * #353 - improve support for single-file apps (@0xced)
 * #379 - simplify assembly loading (@0xced)
 * #366 - reader options callback to expose `LoggingLevelSwitch` (@0xced)
 * #380, #381 - fix tests on .NET 4.8 (@0xced)
 * #378 - fix error handling in build script (@0xced)

### CODE REVIEW

**Comment by 0xced** [comment]
I guess the title of this pull request could be renamed to **4.0.0 Release** since ab5d7a4415ab145d79b9fd776443217c32127718 is going to be merged?

**Comment by nblumhardt** [comment]
Back to draft because the release notes need updating.

**Comment by 0xced** [comment]
After merging #366 there will be 3 mentions of `Since version 4.0.0` in the README. That should probably be updated to `Since version 7.0.0` to reflect the recent versioning change.

**Comment by nblumhardt** [comment]
Ready to go! 😎

**Pull request merged**
